"""
Summary router — stub for Phase 4 (watsonx.ai AI summary).
Returns placeholder stats in Phase 2; full LLM integration added in Phase 4.
"""

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from database import get_db
from models import Disruption, Shipment, Fleet, ColdChainReading

router = APIRouter(prefix="/api/summary", tags=["Summary"])


@router.get("/stats")
def get_summary_stats(db: Session = Depends(get_db)):
    """Return raw operational statistics used to build the AI summary prompt."""
    active_disruptions = db.query(Disruption).filter(Disruption.status == "active").count()
    shipments_at_risk = (
        db.query(Shipment)
        .filter(Shipment.status.in_(["at_risk", "delayed"]))
        .count()
    )
    idle_fleet = db.query(Fleet).filter(Fleet.status == "idle").count()
    cold_chain_excursions = (
        db.query(ColdChainReading)
        .filter(ColdChainReading.excursion == True)  # noqa: E712
        .count()
    )
    critical_excursions = (
        db.query(ColdChainReading)
        .filter(
            ColdChainReading.excursion == True,  # noqa: E712
            ColdChainReading.severity == "critical",
        )
        .count()
    )
    return {
        "active_disruptions": active_disruptions,
        "shipments_at_risk": shipments_at_risk,
        "idle_fleet": idle_fleet,
        "cold_chain_excursions": cold_chain_excursions,
        "critical_excursions": critical_excursions,
    }


@router.get("")
def get_summary(db: Session = Depends(get_db)):
    """
    AI operational summary endpoint.
    Phase 2: returns stats only (no LLM call yet).
    Phase 4 will add IBM watsonx.ai Granite model generation.
    """
    stats = get_summary_stats(db)
    return {
        "summary": (
            f"[AI summary will be generated by IBM watsonx.ai in Phase 4] "
            f"Current status: {stats['active_disruptions']} active disruption(s), "
            f"{stats['shipments_at_risk']} shipment(s) at risk, "
            f"{stats['idle_fleet']} idle fleet vehicle(s), "
            f"{stats['cold_chain_excursions']} cold-chain excursion(s) "
            f"({stats['critical_excursions']} critical)."
        ),
        "stats": stats,
        "ai_generated": False,
    }
